/**
 * Katalog ikon pro projekty a úkoly.
 *
 * Ikona se ukládá jako string:
 *  - emoji rovnou ("💪")
 *  - kreslená ikona s předponou ("lucide:Dumbbell")
 *
 * Díky předponě je starý zápis (holé emoji) pořád platný a nic se nemigruje.
 * Samotné komponenty ikon žijí v `components/ui/icon-picker.tsx` - tady je jen
 * data a jména, aby šel katalog použít i bez Reactu.
 */

export const LUCIDE_PREFIX = "lucide:";

/** "lucide:Dumbbell" -> "Dumbbell", emoji -> null. */
export function lucideNameOf(icon: string): string | null {
  return icon.startsWith(LUCIDE_PREFIX) ? icon.slice(LUCIDE_PREFIX.length) : null;
}

export function lucideRef(name: string): string {
  return `${LUCIDE_PREFIX}${name}`;
}

/**
 * Klíčová slova se hledají bez diakritiky - uživatel píše "kava", ne "káva".
 */
export function normalizeQuery(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim();
}

export interface IconEntry {
  /** Emoji znak nebo jméno lucide ikony. */
  value: string;
  /** Slova pro hledání, oddělená mezerou. */
  keywords: string;
}

export interface IconGroup {
  label: string;
  items: IconEntry[];
}

function group(label: string, pairs: [string, string][]): IconGroup {
  return { label, items: pairs.map(([value, keywords]) => ({ value, keywords })) };
}

// --- emoji ------------------------------------------------------------------

export const EMOJI_GROUPS: IconGroup[] = [
  group("Práce a peníze", [
    ["💼", "prace kufrik business"],
    ["🖥️", "pocitac kancelar"],
    ["💻", "notebook laptop"],
    ["📈", "rust graf nahoru"],
    ["📉", "pokles graf dolu"],
    ["📊", "statistika graf sloupce"],
    ["💰", "penize pytel"],
    ["💵", "bankovky penize"],
    ["💳", "karta platba"],
    ["🏦", "banka"],
    ["🧾", "uctenka faktura"],
    ["📋", "seznam schranka"],
    ["📌", "pripnout spendlik"],
    ["🗂️", "slozky rozdelovac"],
    ["📁", "slozka"],
    ["📂", "otevrena slozka"],
    ["🗃️", "kartoteka archiv"],
    ["📅", "kalendar datum"],
    ["🗓️", "kalendar plan"],
    ["⏰", "budik cas alarm"],
    ["⏳", "presypaci hodiny cas"],
    ["🕐", "hodiny cas"],
    ["📞", "telefon hovor"],
    ["📱", "mobil telefon"],
    ["📧", "email mail posta"],
    ["✉️", "dopis obalka"],
    ["🤝", "dohoda ruce jednani"],
    ["🎯", "cil terc"],
    ["🏆", "trofej vyhra"],
    ["🥇", "zlata medaile prvni"],
    ["🏅", "medaile"],
    ["📢", "megafon oznameni"],
    ["🔔", "zvonek pripominka"],
    ["🔑", "klic pristup"],
    ["⚙️", "nastaveni ozubene kolo"],
    ["🧰", "nastroje kufr"],
    ["🖇️", "sponky spojit"],
    ["🗒️", "blok poznamky"],
  ]),
  group("Sport a tělo", [
    ["💪", "sila biceps posilovna fitness"],
    ["🏋️", "vzpirani posilovna cinka"],
    ["🤸", "gymnastika kolo"],
    ["🏃", "beh bezec running"],
    ["🚶", "chuze kroky walking"],
    ["🧘", "meditace joga klid"],
    ["🚴", "kolo cyklistika"],
    ["🚵", "horske kolo mtb"],
    ["🏊", "plavani bazen"],
    ["🥊", "box rukavice"],
    ["🥋", "judo karate kimono"],
    ["⚽", "fotbal mic"],
    ["🏀", "basketbal"],
    ["🏐", "volejbal"],
    ["🎾", "tenis"],
    ["🏓", "pingpong stolni tenis"],
    ["🏸", "badminton"],
    ["🏒", "hokej"],
    ["⚾", "baseball"],
    ["🏈", "americky fotbal"],
    ["⛷️", "lyze skiing"],
    ["🏂", "snowboard"],
    ["🧗", "lezeni horolezectvi climbing"],
    ["🪂", "paragliding seskok"],
    ["🏄", "surfing"],
    ["🤺", "serm"],
    ["🛹", "skateboard"],
    ["⛸️", "krasobrusleni brusle"],
    ["🏹", "lukostrelba luk"],
    ["⛳", "golf"],
    ["🎳", "bowling"],
    ["👟", "tenisky obuv beh"],
    ["🦵", "noha"],
    ["🦶", "chodidlo kroky"],
  ]),
  group("Zdraví a klid", [
    ["❤️", "srdce zdravi laska"],
    ["🫀", "srdce organ tep"],
    ["🧠", "mozek mysl uceni"],
    ["🦷", "zub dentista"],
    ["🦴", "kost"],
    ["🩺", "lekar stetoskop"],
    ["💊", "pilulka lek"],
    ["💉", "injekce vakcina"],
    ["🩹", "naplast zraneni"],
    ["🛌", "spanek postel"],
    ["😴", "spanek unava"],
    ["🚿", "sprcha hygiena"],
    ["🛁", "vana koupel"],
    ["🧼", "mydlo cistota"],
    ["🪥", "zubni kartacek"],
    ["🚭", "nekurak koureni"],
    ["🥤", "piti napoj"],
    ["💧", "voda kapka pitny rezim"],
    ["🌡️", "teplomer teplota"],
    ["⚖️", "vaha hmotnost"],
    ["🧴", "krem lahvicka"],
    ["🌿", "bylina zeleny"],
    ["🕯️", "svicka klid"],
    ["☀️", "slunce rano den"],
    ["🌙", "mesic noc vecer"],
  ]),
  group("Učení a tvoření", [
    ["📖", "kniha cteni"],
    ["📚", "knihy studium"],
    ["📕", "kniha cervena"],
    ["📗", "kniha zelena"],
    ["📘", "kniha modra"],
    ["📓", "zapisnik notes"],
    ["📔", "denik journal"],
    ["📝", "poznamka psani"],
    ["✍️", "psani ruka"],
    ["✏️", "tuzka"],
    ["🖊️", "pero"],
    ["🖌️", "stetec malovani"],
    ["🎨", "malovani paleta umeni"],
    ["🎭", "divadlo maska"],
    ["🎬", "film klapka"],
    ["📷", "foto fotoaparat"],
    ["🎥", "kamera video"],
    ["🎤", "mikrofon zpev"],
    ["🎧", "sluchatka hudba"],
    ["🎵", "hudba nota"],
    ["🎹", "klavir piano"],
    ["🎸", "kytara"],
    ["🥁", "bici drum"],
    ["🎻", "violoncello housle"],
    ["🎺", "trumpeta"],
    ["♟️", "sachy strategie"],
    ["🧩", "puzzle skladacka"],
    ["🎲", "kostka hra"],
    ["🎮", "hra ovladac gaming"],
    ["🔬", "mikroskop veda"],
    ["🔭", "teleskop hvezdy"],
    ["🧪", "zkumavka chemie"],
    ["🧬", "dna genetika"],
    ["🗣️", "mluveni jazyk rec"],
    ["🌍", "svet zeme jazyky"],
    ["💡", "zarovka idea napad"],
  ]),
  group("Jídlo a pití", [
    ["🍎", "jablko ovoce"],
    ["🍌", "banan ovoce"],
    ["🍇", "hrozny ovoce"],
    ["🍓", "jahoda ovoce"],
    ["🍊", "pomeranc ovoce"],
    ["🥑", "avokado"],
    ["🥦", "brokolice zelenina"],
    ["🥕", "mrkev zelenina"],
    ["🌽", "kukurice"],
    ["🍅", "rajce zelenina"],
    ["🥔", "brambora"],
    ["🍞", "chleba peceni"],
    ["🥐", "croissant peciva"],
    ["🧀", "syr"],
    ["🥚", "vejce protein"],
    ["🍗", "kure maso"],
    ["🥩", "steak maso protein"],
    ["🐟", "ryba"],
    ["🍚", "ryze"],
    ["🍜", "polevka nudle"],
    ["🍝", "spagety testoviny"],
    ["🍕", "pizza"],
    ["🍔", "hamburger"],
    ["🥗", "salat zdrave"],
    ["🍰", "dort zakusek"],
    ["🍫", "cokolada"],
    ["🍪", "susenka"],
    ["🍯", "med"],
    ["☕", "kafe kava"],
    ["🍵", "caj"],
    ["🥛", "mleko"],
    ["🍺", "pivo alkohol"],
    ["🍷", "vino alkohol"],
  ]),
  group("Technika", [
    ["⌨️", "klavesnice psani"],
    ["🖱️", "mys klik"],
    ["🖨️", "tiskarna"],
    ["💾", "disketa ulozit"],
    ["🗄️", "server skrin"],
    ["🔌", "zasuvka napajeni"],
    ["🔋", "baterie energie"],
    ["🔦", "svitilna baterka"],
    ["📡", "satelit antena"],
    ["🛰️", "satelit vesmir"],
    ["📺", "televize"],
    ["📻", "radio"],
    ["🎙️", "mikrofon studio podcast"],
    ["⏱️", "stopky mereni"],
    ["⏲️", "casovac timer"],
    ["🧮", "kalkulacka pocty"],
    ["🔍", "lupa hledani"],
    ["🧲", "magnet"],
    ["⚡", "blesk energie rychlost"],
    ["🔧", "klic nastroj"],
    ["🔨", "kladivo"],
    ["🪛", "sroubovak"],
    ["🚀", "raketa start rychlost"],
    ["🛠️", "nastroje oprava"],
  ]),
  group("Doprava a cesty", [
    ["🚗", "auto"],
    ["🚕", "taxi"],
    ["🚙", "auto suv"],
    ["🚌", "autobus"],
    ["🏎️", "formule rychlost"],
    ["🚑", "sanitka"],
    ["🛵", "skutr"],
    ["🏍️", "motorka"],
    ["🚲", "kolo bicykl"],
    ["🛴", "kolobezka"],
    ["🚂", "vlak lokomotiva"],
    ["🚇", "metro"],
    ["✈️", "letadlo let"],
    ["🛫", "odlet letadlo"],
    ["🚁", "helikoptera"],
    ["⛵", "plachetnice more"],
    ["🚢", "lod"],
    ["🗺️", "mapa cesta"],
    ["🧭", "kompas smer"],
    ["🏕️", "kemp priroda"],
    ["🧳", "kufr cestovani"],
    ["🎒", "batoh"],
  ]),
  group("Příroda a zvířata", [
    ["🌱", "klicek rust semenacek"],
    ["🌳", "strom"],
    ["🌲", "jehlicnan les"],
    ["🌴", "palma dovolena"],
    ["🌵", "kaktus"],
    ["🍀", "ctyrlistek stesti"],
    ["🌸", "kvet sakura"],
    ["🌷", "tulipan kvetina"],
    ["🌹", "ruze kvetina"],
    ["🌻", "slunecnice"],
    ["🍁", "list javor podzim"],
    ["🌾", "obili pole"],
    ["🔥", "ohen serie streak"],
    ["🌊", "vlna voda more"],
    ["⛰️", "hora vrchol"],
    ["🏔️", "hora snih vrchol"],
    ["🌋", "vulkan"],
    ["🏝️", "ostrov dovolena"],
    ["⭐", "hvezda"],
    ["🌟", "hvezda zarici"],
    ["✨", "jiskry magie"],
    ["🌈", "duha"],
    ["☁️", "mrak oblacno"],
    ["🌧️", "dest"],
    ["❄️", "snih zima"],
    ["🐶", "pes"],
    ["🐱", "kocka"],
    ["🐴", "kun"],
    ["🦁", "lev odvaha"],
    ["🐺", "vlk"],
    ["🦅", "orel"],
    ["🐝", "pcela pracovitost"],
    ["🐢", "zelva pomalu"],
    ["🦈", "zralok"],
  ]),
  group("Symboly", [
    ["✅", "hotovo splneno"],
    ["☑️", "zaskrtnuto"],
    ["✔️", "fajfka ok"],
    ["❌", "ne krizek chyba"],
    ["❗", "pozor dulezite"],
    ["❓", "otazka"],
    ["⚠️", "varovani pozor"],
    ["🚫", "zakaz stop"],
    ["♻️", "recyklace opakovani"],
    ["🔄", "obnovit opakovat"],
    ["🔁", "opakovat smycka"],
    ["➕", "plus pridat"],
    ["➖", "minus odebrat"],
    ["🟢", "zelena ok"],
    ["🟡", "zluta pozor"],
    ["🔴", "cervena stop"],
    ["🔵", "modra"],
    ["🟠", "oranzova"],
    ["🟣", "fialova"],
    ["🔺", "trojuhelnik nahoru"],
    ["🔷", "diamant modry"],
    ["💠", "diamant"],
    ["♠️", "piky karty"],
    ["♥️", "srdce karty"],
    ["🆗", "ok"],
    ["🔝", "top nahoru"],
    ["💯", "sto procent"],
    ["🎉", "oslava party"],
    ["🎊", "konfety"],
    ["🏁", "cil vlajka finish"],
    ["🚩", "vlajka oznaceni"],
    ["👍", "palec nahoru dobre"],
    ["👊", "pest odhodlani"],
    ["🙌", "ruce nahoru radost"],
    ["🤞", "drzim palce"],
    ["👑", "korona kral"],
    ["💎", "diamant hodnota"],
    ["🔒", "zamek zamceno"],
    ["🔓", "odemceno"],
    ["🎁", "darek"],
  ]),
];

// --- kreslené ikony (lucide) -------------------------------------------------

/**
 * Jména musí odpovídat exportům z `lucide-react` - mapa komponent v
 * `icon-picker.tsx` je importuje jmenovitě, aby se do balíku nedostalo
 * všech 1500 ikon knihovny.
 */
export const LUCIDE_GROUPS: IconGroup[] = [
  group("Práce a peníze", [
    ["Briefcase", "prace kufrik business"],
    ["BriefcaseBusiness", "prace business"],
    ["Building2", "firma budova"],
    ["Presentation", "prezentace"],
    ["LineChart", "graf vyvoj"],
    ["BarChart3", "graf sloupce statistika"],
    ["PieChart", "graf kolac"],
    ["TrendingUp", "rust nahoru"],
    ["TrendingDown", "pokles dolu"],
    ["Target", "cil terc"],
    ["Trophy", "trofej vyhra"],
    ["Medal", "medaile"],
    ["Award", "oceneni"],
    ["Crown", "korona kral"],
    ["Rocket", "raketa start"],
    ["Handshake", "dohoda jednani"],
    ["Users", "lidi tym"],
    ["Mail", "email posta"],
    ["MessageSquare", "zprava chat"],
    ["Phone", "telefon hovor"],
    ["PhoneCall", "hovor volani"],
    ["Calendar", "kalendar datum"],
    ["CalendarCheck", "kalendar splneno"],
    ["Clock", "hodiny cas"],
    ["Timer", "casovac stopky"],
    ["Hourglass", "presypaci hodiny"],
    ["ClipboardList", "seznam schranka"],
    ["ClipboardCheck", "seznam splneno"],
    ["FileText", "dokument soubor"],
    ["Folder", "slozka"],
    ["FolderOpen", "otevrena slozka"],
    ["Archive", "archiv"],
    ["Inbox", "prichozi"],
    ["Send", "poslat"],
    ["Megaphone", "megafon oznameni"],
    ["Bell", "zvonek pripominka"],
    ["Bookmark", "zalozka"],
    ["Tag", "znacka tag"],
    ["Receipt", "uctenka"],
    ["Wallet", "penezenka"],
    ["CreditCard", "karta platba"],
    ["Banknote", "bankovka penize"],
    ["Coins", "mince penize"],
    ["PiggyBank", "sporeni prasatko"],
    ["Calculator", "kalkulacka"],
    ["Landmark", "banka instituce"],
    ["Store", "obchod prodejna"],
    ["ShoppingCart", "kosik nakup"],
    ["Package", "balik zasilka"],
    ["Truck", "kamion doprava"],
    ["Scale", "vaha spravedlnost"],
    ["Percent", "procenta"],
  ]),
  group("Sport a tělo", [
    ["Dumbbell", "cinka posilovna fitness sila"],
    ["Bike", "kolo cyklistika"],
    ["Footprints", "kroky chuze beh"],
    ["PersonStanding", "clovek postava"],
    ["HeartPulse", "tep srdce kardio"],
    ["Heart", "srdce"],
    ["Activity", "aktivita puls"],
    ["Waves", "voda plavani vlny"],
    ["Mountain", "hora vrchol"],
    ["MountainSnow", "hora snih"],
    ["Flame", "ohen serie streak"],
    ["Zap", "blesk energie"],
    ["Droplet", "kapka voda"],
    ["Droplets", "voda pitny rezim"],
    ["Trees", "les priroda"],
    ["Sprout", "klicek rust"],
    ["Leaf", "list zeleny"],
    ["Flower2", "kvetina"],
    ["Sun", "slunce den"],
    ["Moon", "mesic noc"],
    ["Sunrise", "vychod rano"],
    ["Sunset", "zapad vecer"],
    ["Bed", "postel spanek"],
    ["Brain", "mozek mysl"],
    ["Bone", "kost"],
    ["Eye", "oko zrak"],
    ["Hand", "ruka"],
    ["Stethoscope", "lekar stetoskop"],
    ["Pill", "pilulka lek"],
    ["Syringe", "injekce"],
    ["Bandage", "naplast"],
    ["Thermometer", "teplomer"],
    ["ShieldCheck", "ochrana stit"],
  ]),
  group("Jídlo a pití", [
    ["Apple", "jablko ovoce"],
    ["Carrot", "mrkev zelenina"],
    ["Salad", "salat zdrave"],
    ["Beef", "maso steak protein"],
    ["Fish", "ryba"],
    ["Egg", "vejce protein"],
    ["Sandwich", "sendvic"],
    ["Pizza", "pizza"],
    ["Croissant", "peciva"],
    ["Cookie", "susenka"],
    ["IceCream", "zmrzlina"],
    ["Coffee", "kava kafe"],
    ["CupSoda", "napoj piti"],
    ["Milk", "mleko"],
    ["Wine", "vino"],
    ["Beer", "pivo"],
    ["Utensils", "jidlo pribor"],
    ["ChefHat", "kuchar vareni"],
  ]),
  group("Učení a tvoření", [
    ["Book", "kniha"],
    ["BookOpen", "cteni kniha"],
    ["BookMarked", "kniha zalozka"],
    ["Library", "knihovna studium"],
    ["GraduationCap", "skola studium diplom"],
    ["Pencil", "tuzka psani"],
    ["PenTool", "pero kresleni"],
    ["Highlighter", "zvyraznovac"],
    ["NotebookPen", "zapisnik psani"],
    ["StickyNote", "poznamka"],
    ["Languages", "jazyky preklad"],
    ["Globe", "svet zeme"],
    ["Compass", "kompas smer"],
    ["Map", "mapa"],
    ["MapPin", "misto pin"],
    ["Search", "hledani lupa"],
    ["Lightbulb", "zarovka napad"],
    ["Puzzle", "puzzle skladacka"],
    ["Gamepad2", "hra ovladac"],
    ["Dice5", "kostka hra"],
    ["Music", "hudba nota"],
    ["Headphones", "sluchatka"],
    ["Mic", "mikrofon"],
    ["Guitar", "kytara"],
    ["Piano", "klavir"],
    ["Drum", "bici"],
    ["Radio", "radio"],
    ["Film", "film"],
    ["Clapperboard", "klapka film"],
    ["Camera", "foto"],
    ["Video", "video kamera"],
    ["Image", "obrazek"],
    ["Palette", "paleta barvy"],
    ["Brush", "stetec"],
    ["Scissors", "nuzky"],
    ["Ruler", "pravitko"],
    ["Shapes", "tvary"],
    ["Sparkles", "jiskry magie"],
    ["Star", "hvezda"],
    ["Feather", "pero lehkost"],
    ["Quote", "citat"],
    ["Type", "text pismo"],
    ["Microscope", "mikroskop veda"],
    ["Telescope", "teleskop hvezdy"],
    ["FlaskConical", "zkumavka chemie"],
    ["Dna", "dna genetika"],
    ["Atom", "atom fyzika"],
  ]),
  group("Technika", [
    ["Laptop", "notebook pocitac"],
    ["Monitor", "monitor obrazovka"],
    ["Smartphone", "mobil telefon"],
    ["Tablet", "tablet"],
    ["Keyboard", "klavesnice"],
    ["Mouse", "mys"],
    ["MousePointer", "kurzor klik"],
    ["HardDrive", "disk"],
    ["Server", "server"],
    ["Database", "databaze"],
    ["Cpu", "procesor cip"],
    ["Wifi", "wifi sit"],
    ["Cloud", "cloud mrak"],
    ["Download", "stahnout"],
    ["Upload", "nahrat"],
    ["RefreshCw", "obnovit synchronizace"],
    ["RotateCcw", "vratit zpet"],
    ["Settings", "nastaveni ozubene kolo"],
    ["Wrench", "klic nastroj"],
    ["Hammer", "kladivo"],
    ["Plug", "zasuvka napajeni"],
    ["BatteryCharging", "baterie nabijeni"],
    ["Power", "vypinac"],
    ["Terminal", "terminal prikaz"],
    ["Code", "kod programovani"],
    ["GitBranch", "git vetev"],
    ["Github", "github"],
    ["Bug", "chyba bug"],
    ["Lock", "zamek zamceno"],
    ["Key", "klic pristup"],
    ["Fingerprint", "otisk prst"],
    ["QrCode", "qr kod"],
    ["Printer", "tiskarna"],
    ["Save", "ulozit"],
    ["Link", "odkaz"],
    ["Paperclip", "sponka priloha"],
    ["Gauge", "merak tempo"],
    ["SlidersHorizontal", "nastaveni tahla"],
  ]),
  group("Doprava a cesty", [
    ["Car", "auto"],
    ["Bus", "autobus"],
    ["Train", "vlak"],
    ["TrainFront", "vlak souprava"],
    ["Plane", "letadlo"],
    ["PlaneTakeoff", "odlet let"],
    ["Ship", "lod"],
    ["Sailboat", "plachetnice"],
    ["Anchor", "kotva"],
    ["Fuel", "palivo benzin"],
    ["Navigation", "navigace smer"],
    ["Route", "trasa cesta"],
    ["Milestone", "milnik"],
    ["Flag", "vlajka"],
    ["FlagTriangleRight", "vlajka cil"],
    ["Tent", "kemp stan"],
    ["Luggage", "kufr cestovani"],
    ["Backpack", "batoh"],
  ]),
  group("Domov a zvířata", [
    ["Home", "domov dum"],
    ["DoorOpen", "dvere vstup"],
    ["Sofa", "gauc odpocinek"],
    ["Lamp", "lampa svetlo"],
    ["Bath", "vana koupelna"],
    ["ShowerHead", "sprcha"],
    ["WashingMachine", "pracka"],
    ["Refrigerator", "lednice"],
    ["Warehouse", "sklad"],
    ["Dog", "pes"],
    ["Cat", "kocka"],
    ["Bird", "ptak"],
    ["Rabbit", "zajic"],
    ["Turtle", "zelva"],
    ["Snail", "slimak pomalu"],
    ["PawPrint", "tlapka zvire"],
    ["Baby", "dite"],
    ["Smile", "usmev nalada"],
    ["ThumbsUp", "palec dobre"],
    ["PartyPopper", "oslava party"],
    ["Gift", "darek"],
    ["Cake", "dort narozeniny"],
    ["Ticket", "vstupenka"],
  ]),
  group("Značky a stavy", [
    ["Check", "hotovo fajfka"],
    ["CheckCheck", "vse hotovo"],
    ["Plus", "plus pridat"],
    ["Minus", "minus odebrat"],
    ["X", "krizek zrusit"],
    ["ArrowUp", "nahoru"],
    ["ArrowRight", "vpravo dal"],
    ["Repeat", "opakovat"],
    ["Shuffle", "zamichat"],
    ["ListTodo", "seznam ukolu"],
    ["ListChecks", "seznam splneno"],
    ["LayoutGrid", "mrizka dlazdice"],
    ["Filter", "filtr"],
    ["Crosshair", "zamereni cil"],
    ["Focus", "zaostreni"],
    ["Aperture", "objektiv"],
    ["Infinity", "nekonecno"],
    ["Hash", "hashtag"],
    ["AtSign", "zavinac"],
    ["Asterisk", "hvezdicka"],
    ["Circle", "kruh"],
    ["Square", "ctverec"],
    ["Triangle", "trojuhelnik"],
    ["Diamond", "diamant"],
    ["Hexagon", "sestiuhelnik"],
    ["Octagon", "osmiuhelnik"],
  ]),
];

export const DEFAULT_PROJECT_ICON = "📁";
export const DEFAULT_TASK_ICON = "📝";
/**
 * Výchozí ikona složky ve stromu winů. Kreslená, ne emoji - složka bez vybrané
 * ikony se odjakživa kreslila `Folder` z lucide a starší data se nemigrovala,
 * takže musí zůstat u téhož znaku.
 */
export const DEFAULT_FOLDER_ICON = lucideRef("Folder");

/** Všechny položky jednoho katalogu na plocho - pro hledání. */
export function flattenGroups(groups: IconGroup[]): IconEntry[] {
  return groups.flatMap((g) => g.items);
}

/** Filtr katalogu podle dotazu; prázdný dotaz vrátí skupiny nedotčené. */
export function filterGroups(groups: IconGroup[], query: string): IconGroup[] {
  const q = normalizeQuery(query);
  if (!q) return groups;
  return groups
    .map((g) => ({
      label: g.label,
      items: g.items.filter(
        (i) => i.keywords.includes(q) || normalizeQuery(i.value).includes(q),
      ),
    }))
    .filter((g) => g.items.length > 0);
}
